server:
  port: 8080
debug: true
spring:
  application:
    name: youtube-utils

logging:
  level:
    in.rahulojha.service: debug
    root: info

app:
  config:
    use-ffmpeg: true
    look-in-path: false
    ytDlpPath: C:\\Users\\rahul\\yt-dlp
    ffmpegPath: C:\\Users\\rahul\\yt-dlp\\ffmpeg